import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Terminal, Home, HardDrive, Sparkles, Newspaper, Scale, Usb,
  Trash2, Download, FileCode, ArrowLeft
} from "lucide-react";
import { useIsoSelection } from "@/contexts/IsoSelectionContext";

export default function VentoyBuilder() {
  const [location] = useLocation();
  const { selectedDownloads, removeSelection, clearSelection, selectedCount } = useIsoSelection();

  const generateVentoyJson = () => {
    if (selectedDownloads.length === 0) return;
    const config = {
      theme: { file: "/ventoy/theme.txt" },
      menu_alias: selectedDownloads.map(d => ({
        image: `/${d.distroName.toLowerCase().replace(/\s+/g, "-")}-${d.version}-${d.architecture}.iso`,
        alias: `${d.distroName} ${d.version} (${d.architecture})`
      }))
    };
    const blob = new Blob([JSON.stringify(config, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "ventoy.json";
    a.click();
    URL.revokeObjectURL(url);
  };

  const generateDownloadScript = () => {
    if (selectedDownloads.length === 0) return;
    const lines = [
      "#!/bin/bash",
      "# Ventoy ISO Download Script",
      "# Generated by Linux Distro Directory",
      "",
      "mkdir -p isos",
      "cd isos",
      "",
      ...selectedDownloads.map(d =>
        `wget -c "${d.isoUrl}" -O "${d.distroName.toLowerCase().replace(/\s+/g, "-")}-${d.version}-${d.architecture}.iso"`
      )
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "download-isos.sh";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-50 border-b bg-card border-border">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between gap-6 flex-wrap">
            <Link href="/" data-testid="link-home-logo">
              <div className="flex items-center gap-3 cursor-pointer">
                <div className="w-10 h-10 rounded-md bg-primary flex items-center justify-center">
                  <Terminal className="w-6 h-6 text-primary-foreground" />
                </div>
                <div className="hidden sm:block">
                  <h1 className="font-serif font-bold text-lg text-foreground leading-tight">
                    Linux Distro
                  </h1>
                  <p className="text-xs text-muted-foreground -mt-0.5">Directory</p>
                </div>
              </div>
            </Link>

            <nav className="flex items-center gap-1 flex-wrap">
              <Link href="/">
                <Button
                  variant={location === "/" ? "secondary" : "ghost"}
                  size="sm"
                  data-testid="link-nav-home"
                >
                  <Home className="w-4 h-4 sm:mr-2" />
                  <span className="hidden sm:inline">Home</span>
                </Button>
              </Link>

              <Link href="/matcher">
                <Button
                  variant={location === "/matcher" ? "secondary" : "ghost"}
                  size="sm"
                  data-testid="link-nav-matcher"
                >
                  <Sparkles className="w-4 h-4 sm:mr-2" />
                  <span className="hidden sm:inline">Distro Matcher</span>
                </Button>
              </Link>
              <Link href="/compare">
                <Button
                  variant={location === "/compare" ? "secondary" : "ghost"}
                  size="sm"
                  data-testid="link-nav-compare"
                >
                  <Scale className="w-4 h-4 sm:mr-2" />
                  <span className="hidden sm:inline">Compare</span>
                </Button>
              </Link>
              <Link href="/ventoy">
                <Button
                  variant={location === "/ventoy" ? "secondary" : "ghost"}
                  size="sm"
                  data-testid="link-nav-ventoy"
                >
                  <Usb className="w-4 h-4 sm:mr-2" />
                  <span className="hidden sm:inline">Ventoy Builder</span>
                  {selectedCount > 0 && (
                    <Badge variant="default" className="ml-1 bg-green-600 text-xs">
                      {selectedCount}
                    </Badge>
                  )}
                </Button>
              </Link>
              <Link href="/news">
                <Button
                  variant={location === "/news" ? "secondary" : "ghost"}
                  size="sm"
                  data-testid="link-nav-news"
                >
                  <Newspaper className="w-4 h-4 sm:mr-2" />
                  <span className="hidden sm:inline">News</span>
                </Button>
              </Link>
            </nav>
          </div>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-6 py-8">
        <div className="mb-8">
          <div className="flex items-center gap-4 mb-2">
            <div className="w-12 h-12 rounded-md bg-green-600 flex items-center justify-center">
              <Usb className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="font-serif text-2xl font-bold">Ventoy Config Builder</h1>
              <p className="text-muted-foreground">Build your multi-boot USB configuration</p>
            </div>
          </div>
        </div>

        {selectedCount === 0 ? (
          <Card className="p-12 text-center">
            <Usb className="w-16 h-16 mx-auto text-muted-foreground mb-4" />
            <h2 className="font-semibold text-lg mb-2">No ISOs Selected</h2>
            <p className="text-muted-foreground mb-6">
              Browse the ISO Library and add ISOs to build your Ventoy configuration.
            </p>
            <Link href="/">
              <Button data-testid="button-browse-isos">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Browse Directory
              </Button>
            </Link>
          </Card>
        ) : (
          <div className="space-y-6">
            <Card className="overflow-hidden">
              <div className="p-4 border-b flex items-center justify-between gap-4 flex-wrap">
                <h2 className="font-semibold">Selected ISOs ({selectedCount})</h2>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={clearSelection}
                  data-testid="button-clear-all"
                >
                  <Trash2 className="w-4 h-4 mr-1" />
                  Clear All
                </Button>
              </div>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Distribution</TableHead>
                    <TableHead>Version</TableHead>
                    <TableHead>Architecture</TableHead>
                    <TableHead>Size</TableHead>
                    <TableHead className="w-[50px]"></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {selectedDownloads.map((download) => (
                    <TableRow key={download.downloadId} data-testid={`row-iso-${download.downloadId}`}>
                      <TableCell className="font-medium" data-testid={`text-distro-${download.downloadId}`}>
                        {download.distroName}
                      </TableCell>
                      <TableCell>
                        <Badge variant="outline" className="font-mono">
                          v{download.version}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <Badge variant="secondary" className="font-mono text-xs">
                          {download.architecture}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-muted-foreground">
                        {download.downloadSize || "Unknown"}
                      </TableCell>
                      <TableCell>
                        <Button
                          size="icon"
                          variant="ghost"
                          onClick={() => removeSelection(download.downloadId)}
                          data-testid={`button-remove-${download.downloadId}`}
                        >
                          <Trash2 className="w-4 h-4 text-muted-foreground" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </Card>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <Card
                className="p-6 hover-elevate cursor-pointer"
                onClick={generateVentoyJson}
                data-testid="button-download-ventoy-json"
              >
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-md bg-primary flex items-center justify-center flex-shrink-0">
                    <FileCode className="w-6 h-6 text-primary-foreground" />
                  </div>
                  <div>
                    <h3 className="font-semibold">Download ventoy.json</h3>
                    <p className="text-sm text-muted-foreground">
                      Menu aliases for Ventoy boot menu
                    </p>
                  </div>
                </div>
              </Card>

              <Card
                className="p-6 hover-elevate cursor-pointer"
                onClick={generateDownloadScript}
                data-testid="button-download-script"
              >
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-md bg-green-600 flex items-center justify-center flex-shrink-0">
                    <Download className="w-6 h-6 text-white" />
                  </div>
                  <div>
                    <h3 className="font-semibold">Get Download Script</h3>
                    <p className="text-sm text-muted-foreground">
                      Bash script to download all ISOs
                    </p>
                  </div>
                </div>
              </Card>
            </div>

            <div className="text-center pt-4">
              <Link href="/">
                <Button variant="outline" data-testid="button-add-more">
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Add More ISOs
                </Button>
              </Link>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
